package com.Facturador.modelo;
// Generated 16-ene-2016 16:35:10 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	private int idCedula;
	private String nombre;
	private Integer telf;
	private String dir;
	

	public Cliente() {
	}

	public Cliente(int idCedula) {
		this.idCedula = idCedula;
	}

	public Cliente(int idCedula, String nombre, Integer telf, String dir) {
		this.idCedula = idCedula;
		this.nombre = nombre;
		this.telf = telf;
		this.dir = dir;
	}

	public int getIdCedula() {
		return this.idCedula;
	}

	public void setIdCedula(int idCedula) {
		this.idCedula = idCedula;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Integer getTelf() {
		return this.telf;
	}

	public void setTelf(Integer telf) {
		this.telf = telf;
	}

	public String getDir() {
		return this.dir;
	}

	public void setDir(String dir) {
		this.dir = dir;
	}

	/**public Set<Pedido> getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set<Pedido> pedidos) {
		this.pedidos = pedidos;
	}
	**/

}
