package com.Facturador.modelo;
// Generated 18-ene-2016 15:29:18 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	private int idCedula;
	private String nombre;
	private String telf;
	private String dir;
	private Set<Compras> comprases = new HashSet<Compras>(0);

	public Cliente() {
	}

	public Cliente(int idCedula, String nombre, String telf, String dir) {
		this.idCedula = idCedula;
		this.nombre = nombre;
		this.telf = telf;
		this.dir = dir;
	}

	public Cliente(int idCedula, String nombre, String telf, String dir, Set<Compras> comprases) {
		this.idCedula = idCedula;
		this.nombre = nombre;
		this.telf = telf;
		this.dir = dir;
		this.comprases = comprases;
	}

	public int getIdCedula() {
		return this.idCedula;
	}

	public void setIdCedula(int idCedula) {
		this.idCedula = idCedula;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getTelf() {
		return this.telf;
	}

	public void setTelf(String telf) {
		this.telf = telf;
	}

	public String getDir() {
		return this.dir;
	}

	public void setDir(String dir) {
		this.dir = dir;
	}

	public Set<Compras> getComprases() {
		return this.comprases;
	}

	public void setComprases(Set<Compras> comprases) {
		this.comprases = comprases;
	}

}
