package com.Facturador.modelo;
// Generated 18-ene-2016 15:29:18 by Hibernate Tools 4.0.0

/**
 * ComprasId generated by hbm2java
 */
public class ComprasId implements java.io.Serializable {

	private int jefeIdjefe;
	private int clienteIdCedula;
	private int productoIdproducto;
	private int codigoCompra;

	public ComprasId() {
	}

	public ComprasId(int jefeIdjefe, int clienteIdCedula, int productoIdproducto, int codigoCompra) {
		this.jefeIdjefe = jefeIdjefe;
		this.clienteIdCedula = clienteIdCedula;
		this.productoIdproducto = productoIdproducto;
		this.codigoCompra = codigoCompra;
	}

	public int getJefeIdjefe() {
		return this.jefeIdjefe;
	}

	public void setJefeIdjefe(int jefeIdjefe) {
		this.jefeIdjefe = jefeIdjefe;
	}

	public int getClienteIdCedula() {
		return this.clienteIdCedula;
	}

	public void setClienteIdCedula(int clienteIdCedula) {
		this.clienteIdCedula = clienteIdCedula;
	}

	public int getProductoIdproducto() {
		return this.productoIdproducto;
	}

	public void setProductoIdproducto(int productoIdproducto) {
		this.productoIdproducto = productoIdproducto;
	}

	public int getCodigoCompra() {
		return this.codigoCompra;
	}

	public void setCodigoCompra(int codigoCompra) {
		this.codigoCompra = codigoCompra;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ComprasId))
			return false;
		ComprasId castOther = (ComprasId) other;

		return (this.getJefeIdjefe() == castOther.getJefeIdjefe())
				&& (this.getClienteIdCedula() == castOther.getClienteIdCedula())
				&& (this.getProductoIdproducto() == castOther.getProductoIdproducto())
				&& (this.getCodigoCompra() == castOther.getCodigoCompra());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getJefeIdjefe();
		result = 37 * result + this.getClienteIdCedula();
		result = 37 * result + this.getProductoIdproducto();
		result = 37 * result + this.getCodigoCompra();
		return result;
	}

}
