package com.Facturador.modelo;
// Generated 18-ene-2016 15:29:18 by Hibernate Tools 4.0.0

/**
 * Compras generated by hbm2java
 */
public class Compras implements java.io.Serializable {

	private ComprasId id;
	private Producto producto;
	private Cliente cliente;
	private Encargado encargado;
	private String fecha;

	public Compras() {
	}

	public Compras(ComprasId id, Producto producto, Cliente cliente, Encargado encargado, String fecha) {
		this.id = id;
		this.producto = producto;
		this.cliente = cliente;
		this.encargado = encargado;
		this.fecha = fecha;
	}

	public ComprasId getId() {
		return this.id;
	}

	public void setId(ComprasId id) {
		this.id = id;
	}

	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public Encargado getEncargado() {
		return this.encargado;
	}

	public void setEncargado(Encargado encargado) {
		this.encargado = encargado;
	}

	public String getFecha() {
		return this.fecha;
	}

	public void setFecha(String fecha) {
		this.fecha = fecha;
	}

}
