package com.Facturador.modelo;
// Generated 18-ene-2016 15:29:18 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Encargado generated by hbm2java
 */
public class Encargado implements java.io.Serializable {

	private int idjefe;
	private String nombre;
	private String username;
	private String pass;
	private Set<Compras> comprases = new HashSet<Compras>(0);

	public Encargado() {
	}

	public Encargado(int idjefe, String nombre, String username, String pass) {
		this.idjefe = idjefe;
		this.nombre = nombre;
		this.username = username;
		this.pass = pass;
	}

	public Encargado(int idjefe, String nombre, String username, String pass, Set<Compras> comprases) {
		this.idjefe = idjefe;
		this.nombre = nombre;
		this.username = username;
		this.pass = pass;
		this.comprases = comprases;
	}

	public int getIdjefe() {
		return this.idjefe;
	}

	public void setIdjefe(int idjefe) {
		this.idjefe = idjefe;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	public Set<Compras> getComprases() {
		return this.comprases;
	}

	public void setComprases(Set<Compras> comprases) {
		this.comprases = comprases;
	}

}
