package com.Facturador.modelo;
// Generated 16-ene-2016 16:35:10 by Hibernate Tools 4.0.0

/**
 * Pedido generated by hbm2java
 */
public class Pedido implements java.io.Serializable {

	private PedidoId id;
	private Encargado encargado;
	private Cliente cliente;
	private String fecha;

	public Pedido() {
	}

	public Pedido(PedidoId id, Encargado encargado, Cliente cliente) {
		this.id = id;
		this.encargado = encargado;
		this.cliente = cliente;
	}

	public Pedido(PedidoId id, Encargado encargado, Cliente cliente, String fecha) {
		this.id = id;
		this.encargado = encargado;
		this.cliente = cliente;
		this.fecha = fecha;
	}

	public PedidoId getId() {
		return this.id;
	}

	public void setId(PedidoId id) {
		this.id = id;
	}

	public Encargado getEncargado() {
		return this.encargado;
	}

	public void setEncargado(Encargado encargado) {
		this.encargado = encargado;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public String getFecha() {
		return this.fecha;
	}

	public void setFecha(String fecha) {
		this.fecha = fecha;
	}

}
