package com.Facturador.modelo;
// Generated 18-ene-2016 15:29:18 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable {

	private int idproducto;
	private Proveedor proveedor;
	private String nombre;
	private BigDecimal precio;
	private Integer stock;
	private Set<Compras> comprases = new HashSet<Compras>(0);

	public Producto() {
	}

	public Producto(int idproducto, String nombre, BigDecimal precio, Integer stock) {
		this.idproducto = idproducto;
		this.nombre = nombre;
		this.precio = precio;
		this.stock = stock;
	}

	public Producto(int idproducto, Proveedor proveedor, String nombre, BigDecimal precio, Integer stock) {
		this.idproducto = idproducto;
		this.proveedor = proveedor;
		this.nombre = nombre;
		this.precio = precio;
		this.stock = stock;
	}

	public int getIdproducto() {
		return this.idproducto;
	}

	public void setIdproducto(int idproducto) {
		this.idproducto = idproducto;
	}

	public Proveedor getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(Proveedor proveedor) {
		this.proveedor = proveedor;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	public Integer getStock() {
		return this.stock;
	}

	public void setStock(Integer stock) {
		this.stock = stock;
	}

	public Set<Compras> getComprases() {
		return this.comprases;
	}

	public void setComprases(Set<Compras> comprases) {
		this.comprases = comprases;
	}

}
