package com.Facturador.modelo;
// Generated 16-ene-2016 16:35:10 by Hibernate Tools 4.0.0

/**
 * ProductoId generated by hbm2java
 */
public class ProductoId implements java.io.Serializable {

	private int idproducto;
	private int proveedorIdproveedor;
	private int encargadoId;

	public ProductoId() {
	}

	public ProductoId(int idproducto, int proveedorIdproveedor, int encargadoId) {
		this.idproducto = idproducto;
		this.proveedorIdproveedor = proveedorIdproveedor;
		this.encargadoId = encargadoId;
	}

	public int getIdproducto() {
		return this.idproducto;
	}

	public void setIdproducto(int idproducto) {
		this.idproducto = idproducto;
	}

	public int getProveedorIdproveedor() {
		return this.proveedorIdproveedor;
	}

	public void setProveedorIdproveedor(int proveedorIdproveedor) {
		this.proveedorIdproveedor = proveedorIdproveedor;
	}

	public int getEncargadoId() {
		return this.encargadoId;
	}

	public void setEncargadoId(int encargadoId) {
		this.encargadoId = encargadoId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductoId))
			return false;
		ProductoId castOther = (ProductoId) other;

		return (this.getIdproducto() == castOther.getIdproducto())
				&& (this.getProveedorIdproveedor() == castOther.getProveedorIdproveedor())
				&& (this.getEncargadoId() == castOther.getEncargadoId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdproducto();
		result = 37 * result + this.getProveedorIdproveedor();
		result = 37 * result + this.getEncargadoId();
		return result;
	}

}
