package com.Facturador.modelo;
// Generated 16-ene-2016 16:35:10 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable {

	private int id;
	private Encargado encargado;
	private Proveedor proveedor;
	private String nombre;
	private BigDecimal precio;
	private int stock;

	public Producto(int id, String nombre, BigDecimal precio) {
		this.id = id;
		this.nombre = nombre;
		this.precio = precio;
	}

	public Producto(int id, Encargado encargado, Proveedor proveedor, String nombre, BigDecimal precio,
			int stock) {
		this.id = id;
		this.encargado = encargado;
		this.proveedor = proveedor;
		this.nombre = nombre;
		this.precio = precio;
		this.stock = stock;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Encargado getEncargado() {
		return this.encargado;
	}

	public void setEncargado(Encargado encargado) {
		this.encargado = encargado;
	}

	public Proveedor getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(Proveedor proveedor) {
		this.proveedor = proveedor;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	public int getStock() {
		return this.stock;
	}

	public void setStock(int stock) {
		this.stock = stock;
	}

}
