package com.Facturador.modelo;
// Generated 18-ene-2016 15:29:18 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor implements java.io.Serializable {

	private String idrif;
	private String nombre;
	private String empresa;
	private String tlf;
	private Set<Producto> productos = new HashSet<Producto>(0);

	public Proveedor() {
	}

	public Proveedor(String idrif, String nombre, String empresa, String tlf) {
		this.idrif = idrif;
		this.nombre = nombre;
		this.empresa = empresa;
		this.tlf = tlf;
	}

	public Proveedor(String idrif, String nombre, String empresa, String tlf, Set<Producto> productos) {
		this.idrif = idrif;
		this.nombre = nombre;
		this.empresa = empresa;
		this.tlf = tlf;
		this.productos = productos;
	}

	public String getIdrif() {
		return this.idrif;
	}

	public void setIdrif(String idrif) {
		this.idrif = idrif;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(String empresa) {
		this.empresa = empresa;
	}

	public String getTlf() {
		return this.tlf;
	}

	public void setTlf(String tlf) {
		this.tlf = tlf;
	}

	public Set<Producto> getProductos() {
		return this.productos;
	}

	public void setProductos(Set<Producto> productos) {
		this.productos = productos;
	}

}
