package com.Facturador.modelo;
// Generated 16-ene-2016 16:35:10 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor implements java.io.Serializable {

	private int idproveedor;
	private String nombre;
	private String rif;
	private String empresa;
	private Set<Producto> productos = new HashSet<Producto>(0);

	public Proveedor() {
	}

	public Proveedor(int idproveedor, String nombre, String rif, String empresa) {
		this.idproveedor = idproveedor;
		this.nombre = nombre;
		this.rif = rif;
		this.empresa = empresa;
	}

	public Proveedor(int idproveedor, String nombre, String rif, String empresa, Set<Producto> productos) {
		this.idproveedor = idproveedor;
		this.nombre = nombre;
		this.rif = rif;
		this.empresa = empresa;
		this.productos = productos;
	}

	public int getIdproveedor() {
		return this.idproveedor;
	}

	public void setIdproveedor(int idproveedor) {
		this.idproveedor = idproveedor;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getRif() {
		return this.rif;
	}

	public void setRif(String rif) {
		this.rif = rif;
	}

	public String getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(String empresa) {
		this.empresa = empresa;
	}

	public Set<Producto> getProductos() {
		return this.productos;
	}

	public void setProductos(Set<Producto> productos) {
		this.productos = productos;
	}

}
