package com.Facturador.modelo;
// Generated 16-ene-2016 0:13:21 by Hibernate Tools 3.4.0.CR1

/**
 * Registroencar generated by hbm2java
 */
public class Registroencar implements java.io.Serializable {

	private String codigo;
	private String nombre;
	private String apellido;

	public Registroencar() {
	}

	public Registroencar(String codigo) {
		this.codigo = codigo;
	}

	public Registroencar(String codigo, String nombre, String apellido) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.apellido = apellido;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

}
