package com.Facturador.modelo;
// Generated 16-ene-2016 0:13:21 by Hibernate Tools 3.4.0.CR1

/**
 * Registroproducto generated by hbm2java
 */
public class Registroproducto implements java.io.Serializable {

	private String codigo;
	private String descripcion;
	private String precio;

	public Registroproducto() {
	}

	public Registroproducto(String codigo) {
		this.codigo = codigo;
	}

	public Registroproducto(String codigo, String descripcion, String precio) {
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.precio = precio;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getPrecio() {
		return this.precio;
	}

	public void setPrecio(String precio) {
		this.precio = precio;
	}

}
